### ISSUE TITLE
feature request: support for local to local backups in zb-pull

### ISSUE THREAD

**Issue by mailinglists35** [exaexa/zfs-backup#1]
I have the backup block device attached locally.
Running zb-pull over ssh to localhost would slow me down.
It would be nice to add support for local to local backup scenario.

**Comment by exaexa** [comment]
Hi!

Mind testing the patch from local-support branch? I don't have a zfs system handy right now.

https://github.com/exaexa/zfs-backup/commit/e589e8f52c4e4465e4cebffdd1f51636d22437b6

Usage: use plain dash instead of user@host to run on localhost.

Thanks!

**Comment by exaexa** [comment]
This was already merged to master. Use '-' as the remote to pull locally. See https://github.com/exaexa/zfs-backup/blob/master/zb-pull#L20
