### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by dhilst** [exaexa/zfs-backup#2]
Hi,

This is a very nice project but I can't see the license anywhere. Add a license so other people now how they are able to use it!!

Regards,

**Comment by exaexa** [comment]
Oh my, this is so small that it shouldn't even have license. Any best idea for something nonintrusive?

**Comment by dhilst** [comment]
Honestly, this is up only to you. Take a read about the main licenses out there and choose the one you feel better with. I'm not an evangelist.

**Comment by exaexa** [comment]
Released free into the public domain.

:]

**Comment by dhilst** [comment]
Thanks!
